openapi: 3.0.0
info:
  version: 1.0.0
  title: Goober API
  description: API for storing goobers and shrine data
servers:
  - url: tbd
paths:
  /goobers:
    get:
      summary: Get all goobers
      responses:
        '200':
          description: A list of goobers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Goober'
    post:
      summary: Create a new goober
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Goober'
      responses:
        '201':
          description: Goober created successfully
components:
  schemas:
    Goober:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        fingerprint:
          type: string
        last_seen:
          type: string
          format: date-time
        cosmetics:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              id:
                type: integer
        history:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
        stats:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              value:
                type: number
      required:
        - name
        - fingerprint