# Use the official PostgreSQL image as the base
FROM postgres:latest

# Set environment variables for PostgreSQL
# These variables are used by the entrypoint script of the official image
ENV POSTGRES_DB=goobers_db
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password