"""empty message

Revision ID: 239252d720ab
Revises: 
Create Date: 2025-11-15 19:29:35.430083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239252d720ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('value_float', sa.Float(), nullable=True),
    sa.Column('value_string', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fingerprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fingerprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fingerprints_fingerprint'), ['fingerprint'], unique=True)

    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fingerprint_id'], ['fingerprints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkins_timestamp'), ['timestamp'], unique=False)

    op.create_table('goobers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('fingerprint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fingerprint_id'], ['fingerprints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goober_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goober_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['goober_id'], ['goobers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goober_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goober_history_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goober_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goober_history_timestamp'))

    op.drop_table('goober_history')
    op.drop_table('goobers')
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkins_timestamp'))

    op.drop_table('checkins')
    with op.batch_alter_table('fingerprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fingerprints_fingerprint'))

    op.drop_table('fingerprints')
    op.drop_table('events')
    # ### end Alembic commands ###
