"""empty message

Revision ID: 3ad96d684aaa
Revises: 
Create Date: 2025-11-15 15:57:40.578322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad96d684aaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goobers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goobers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goobers_fingerprint'), ['fingerprint'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goobers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goobers_fingerprint'))

    op.drop_table('goobers')
    # ### end Alembic commands ###
